services:
    mgp.image.thumbnail_manager:
        class: MGP\ImageBundle\Model\Manager\ThumbnailManager
        arguments: [@doctrine.orm.entity_manager, @translator, @router, %images_per_page%, @liip_imagine.cache.manager]
