language: php

php:
    - 5.5
    - 5.4
env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - moisesgallego+travis@gmail.com