language: php

php:
    - 5.5
env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: phpunit -c app

notifications:
  email:
    - moisesgallego+travis@gmail.com