imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@SFMPicmntBundle/Resources/config/menu.xml" }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_parameters: %kernel.debug%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator: { fallback: en }
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    default_locale: %locale% 
    session: ~
    

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        upload_dir: '/uploads/'
        thumbs_dir: '/uploads/thumbs/'
        server: 'http://picmnt.com'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        metadata_cache_driver: apc
        query_cache_driver: apc
        result_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SFM\PicmntBundle\Entity\User
    template:
        engine: twig
        #theme:  FOSUserBundle::form.html.twig	         
    registration:
        confirmation:
            enabled: true
            from_email: 
                address: admin@picmnt.com
                sender_name: Picmnt Register
    resetting:
        email:
            from_email:
                address:        admin@picmnt.com
                sender_name:    Picmnt Resetting

knp_menu:
    twig: true
    templating: false
    default_renderer: twig

ornicar_gravatar: ~

parameters:
    image_defaults:
        size: 800
        small_size: 250
        category: "all"
        status: 1
        email_noti: 1
    upload_path: "/uploads"
    image_utils:
        upload_path: "uploads/"
        thumbs_path: "uploads/thumbs/"
        