imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@SFMPicmntBundle/Resources/config/menu.xml" }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_parameters: %kernel.debug%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator: { fallback: en }
    trusted_proxies: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    default_locale: %locale% 
    session:
        name: 'picmnt_session'
    

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        images_per_page: %images_per_page%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['MGPMainBundle', 'MGPImageBundle', 'FOSUserBundle']
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        less:
            node: %node%
            node_paths: %node_paths%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        metadata_cache_driver: apc
        query_cache_driver: apc
        result_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MGP\UserBundle\Entity\User
    template:
        engine: twig
        #theme:  FOSUserBundle::form.html.twig	         
    registration:
        confirmation:
            enabled: true
            from_email: 
                address: admin@picmnt.com
                sender_name: Picmnt Register
    resetting:
        email:
            from_email:
                address:        admin@picmnt.com
                sender_name:    Picmnt Resetting

knp_menu:
    twig: true
    templating: false
    default_renderer: twig

ornicar_gravatar: ~

sfm_picmnt:
    image_file:
        size: 800
        category: "all"
        status: 1
        email_notification: 1
        upload_path: "uploads/"

parameters:
    # image_defaults:
    #     size: 800
    #     small_size: 250
    #     category: "all"
    #     status: 1
    #     email_noti: 1
    #     upload_path: "uploads/"
    #     thumbs_path: "uploads/thumbs/"
    upload_path: "uploads"
    avatar_defaults:
        extension: ".jpg"
        upload_big_path: "uploads/avatarbig/"
        upload_small_path: "uploads/avatarsmall"
        big_size: 100
        small_size: 50

liip_imagine:
    filter_sets:
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [270, 270], mode: outbound }
        avatar-small:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            sluggable: true