############################ INDEX CONTROLLER   ###############################
sfm_index:
    resource: "@SFMPicmntBundle/Controller/IndexController.php"
    type:     annotation

sfm_image:
    resource: "@SFMPicmntBundle/Controller/ImageController.php"
    type:     annotation
