services:
    twig.extension.picmnt:
        class: SFM\PicmntBundle\Twig\Extension\PicmntExtension
        arguments: ["@doctrine.orm.entity_manager", "@translator"]
        tags:
            - { name: twig.extension }

    picmnt.utils:
        class: SFM\PicmntBundle\Util\Util
        arguments: ["@doctrine.orm.entity_manager"]

    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }

    ducksboard.widget:
        class: SFM\DucksboardBundle\Adapter\Widget
        arguments: [@sfm.ducksboard.connector]  
        calls:
            - [setApiKey, [%ducksboard_api%]]

    image.utils:
        class: SFM\PicmntBundle\Util\ImageUtil
        arguments: ["@doctrine.orm.entity_manager", "@security.context"]

    picmnt.paginator:
        class: SFM\PicmntBundle\Util\Paginator
        arguments: ["@doctrine.orm.entity_manager"]
        
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
