services:
    sfm_picmnt.menu_builder:
        class: SFM\PicmntBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        
    sfm_picmnt.menu.login:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: sfm_picmnt.menu_builder
        factory_method: createMenuLogin
        arguments: ["@request", "@translator"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: login } # The alias is what is used to retrieve the menu
                
    sfm_picmnt.menu.tabs:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: sfm_picmnt.menu_builder
        factory_method: createMenuTabs
        arguments: ["@request", "@translator", "@security.context"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: tabs } # The alias is what is used to retrieve the menu

    twig.extension.picmnt:
        class: SFM\PicmntBundle\Twig\Extension\PicmntExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    picmnt.utils:
        class: SFM\PicmntBundle\Util\Util
        arguments: ["@doctrine.orm.entity_manager"]